const enLocal = {
  common: {
    panel: 'Panel',
    bag: 'Bag',
    store: 'Store',
    selectLanguage: 'Language',
    loading: 'Loading...',
    split: 'Split',
    upgrade: 'Upgrade',
    notFound: 'NotFound',
    ok: 'OK',
    cancel: 'Cancel',
    copy: 'Copy',
    copyImageSuccess: 'Copy Image Success',
    calcInfo: 'Calculate',
    sum: 'Summary',
    save: 'Save',
    reset: 'Reset',
    optional: 'Optional',
    multiWays: 'Multi Source',
    chooseFeature: 'Choose Prop',
    addedToTarget: 'successfully added to target',
    addedToCache: 'successfully added to cache',
    unit: 'Unit',
    qualities: [
      '',
      '[Normal]',
      '[Magic]',
      '[Rare]',
      '[Perfect Rare]',
      '[Alkatra]',
      '[Deltirama]',
      '[Neptinos]',
      '[Gnosis]',
      '[Alteia]',
    ],
    goodFields: {
      hp: 'Hp',
      mp: 'Mp',
      atk: 'Atk',
      def: 'Def',
      str: 'Str',
      agi: 'Agi',
      int: 'Int',
      mainAttrInc: 'Stats',
      atkSpeed: 'AS',
      moveSpeed: 'MS',
      abilityDamageInc: 'DMG',
      sufferDamageDec: 'DT',
      magicDefInc: 'MagD',
      hpInc: 'HpReg',
      stillDamageInc: 'DOT',
      atkDamageInc: 'DD',
      mpInc: 'IMpR',
      hpRegenInc: 'IHpR',
      sufferCureInc: 'HR',
      missInc: 'Miss',
      punchAsChanceInc: 'CritM',
      punchChanceInc: 'Crit',
      resurrectionTimeDec: 'Resp',
      expInc: 'Exp',
      iceDamageInc: 'Ice',
      fireDamageInc: 'Fire',
      windAttrInc: 'Wind',
      natureAttrInc: 'Earth',
    },
    stage: 'Stage',
    stages: ['', '[Stage1]', '[Stage2]', '[Stage3]', '[Stage4]', '[Stage5]', '[Stage6]'],
    otherType: '[Other]',
    all: 'All',
    categories: {
      Equip: 'Equip',
      Weapon: 'Weapon',
      Helm: 'Helm',
      Armor: 'Armor',
      Ring: 'Ring',
      Wings: 'Wings',
      Material: 'Material',
      Icon: 'Icon',
      Token: 'Token',
      Summoner: 'Summoner',
      Quest: 'Quest',
    },
    unitProps: {
      uhpr: 'HitPointsRegeneration',
      uhpm: 'HitPointsMaximum',
      uabi: 'Abilities',
      utub: 'Ubertip',
      utip: 'Tooltip',
      udty: 'DefenseType',
      umvs: 'SpeedBase',
      ucol: 'CollisionSize',
      unam: 'Name',
      usca: 'Scale',
      ubld: 'BuildTime',
      urtm: 'RepairTime',
      ugor: 'RepairGoldCost',
      ulur: 'RepairLumberCost',
      usid: 'SightRadiusDay',
      util: 'Tilesets',
      umvt: 'MoveType',
      utyp: 'UnitClassification',
      usin: 'SightRadiusNight',
      umvh: 'FlyHeight',
      umdl: 'Model',
      upgr: 'UpgradesUsed',
      usnd: 'SoundSet',
      uico: 'Icon',
      ushw: 'ShadowImageWidth',
      ushh: 'ShadowImageHeight',
      ushx: 'ShadowImageCenterX',
      ushy: 'ShadowImageCenterY',
      ussc: 'SelectionScale',
      uclb: 'BlueTint',
      uclg: 'GreenTint',
      uclr: 'RedTint',
      uhab: 'HeroAbilities',
      uint: 'StartingIntelligence',
      ubba: 'GoldBountyBase',
      ubsi: 'GoldBountySidesPerDie',
      ubdi: 'GoldBountyNumberOfDice',
      ustp: 'StrengthPerLevel',
      uinp: 'IntelligencePerLevel',
      uagp: 'AgilityPerLevel',
      uagi: 'StartingAgility',
      ustr: 'StartingStrength',
      uaen: 'AttacksEnabled',
      urq2: 'RequirementsTier3',
      urq1: 'RequirementsTier2',
      urqc: 'RequirementsTiersUsed',
      uawt: 'AwakenTooltip',
      utpr: 'ReviveTooltip',
      upru: 'ProperNamesUsed',
      uhot: 'Hotkey',
      upro: 'ProperNames',
      ussi: 'ScoreScreenIcon',
      ureq: 'Requirements',
      usei: 'ItemsSold',
      ucam: 'CategoryCampaign',
      ides: 'Description',
      ulfo: 'SoundLoopFadeOutRate',
      ulfi: 'SoundLoopFadeInRate',
      umsl: 'MoveSound',
      ulev: 'Level',
      uspa: 'SpecialArt',
      ufoo: 'FoodCost',
      ucpt: 'CastPoint',
      ucbs: 'CastBackswing',
      udea: 'DeathType',
      ushu: 'ShadowImage',
      ua1t: 'TypeAttackType1',
      ua1b: 'TypeDamageBase1',
      ua1c: 'Cooldown1',
      udp1: 'DamagePoint1',
      ubs1: 'BackswingPoint1',
      ua1s: 'DamageSidesPerDie1',
      ucs1: 'WeaponSound1',
      ua1w: 'WeaponType1',
      ua1m: 'ProjectileArt1',
      umh1: 'ProjectileHoming1',
      ua1r: 'Range1',
      ua1g: 'TargetsAllowed1',
      ulpz: 'ProjectileLaunchZ',
      uacq: 'AcquisitionRange',
      urb1: 'RangeMotionBuffer1',
      ua1z: 'ProjectileSpeed1',
      urac: 'Race',
      uma1: 'MaximumTargets1',
      ua1p: 'AreaOfEffectTargets1',
      ua1q: 'AreaOfEffectSmall1',
      ua1f: 'AreaOfEffectFull1',
      ua1h: 'AreaOfEffectMedium1',
      uhrt: 'HitPointsRegenerationType',
      uhd1: 'DamageFactorMedium1',
      uqd1: 'DamageFactorSmall1',
      upri: 'TypePriority',
      ufle: 'CanFlee',
      uimz: 'ProjectileImpactZ',
      uaap: 'RequiredAnimationAttachments',
      udtm: 'DeathTime',
      uarm: 'ArmorType',
      urun: 'RunSpeed',
      uwal: 'WalkSpeed',
      ubui: 'StructuresBuilt',
      ua1d: 'NumberOfDice1',
      ufor: 'FormationRank',
      utar: 'TargetedAs',
      udef: 'DefenseBase',
      umvf: 'MinimumHeight',
      uslz: 'SelectionZ',
      usma: 'StockMaximum',
      umpr: 'ManaRegeneration',
      ugol: 'GoldCost',
      umpm: 'ManaMaximum',
      ulpx: 'ProjectileLaunchX',
      ulpy: 'ProjectileLaunchY',
      uamn: 'MinimumAttackRange',
      uerd: 'ElevationSampleRadius',
      ucut: '魔法升级说明',
      ucun: '魔法升级名字',
      udaa: 'DefaultActiveAbility',
      umpi: 'ManaInitialAmount',
      ucua: '魔法升级图标',
      uver: 'ModelExtraVersions',
      utcc: 'AllowCustomTeamColor',
      umxp: 'MaxPitch',
      umxr: 'MaxRoll',
      utco: 'TeamColor',
      udep: 'DependencyEquivalents',
      upra: 'PrimaryAttribute',
      umvr: 'TurnRate',
      umis: 'SpeedMinimum',
      uspe: 'CategorySpecial',
      uani: 'RequiredAnimationNames',
      ulum: 'TypeLumberCost',
      usrg: 'StockReplenishInterval',
      usst: 'StockStartDelay',
      uscb: 'ScaleProjectiles',
      uhos: 'DisplayAsNeutralHostile',
      usle: 'Sleeps',
      uhhd: 'HideHeroDeathMessage',
      udro: 'DropItemsOnDeath',
      upoi: 'PointValue',
      ucar: 'TransportedSize',
      uhom: 'HideMinimapDisplay',
      ushr: 'HasWaterShadow',
      uble: 'BlendTime',
      uprw: 'PropulsionWindow',
      uwu1: 'ShowUI1',
      ushb: 'ShadowTexture',
      uubs: 'GroundTexture',
      upat: 'PathingMap',
      umas: 'SpeedMaximum',
      udup: 'DefenseUpgradeBonus',
    },
  },
  views: {
    header: {
      appName: 'QuickSearch',
      items: 'Item',
      heroes: 'Hero',
      bosses: 'Boss',
      repChats: 'Rep Chats',
      activities: 'Activities',
      setWar3Path: 'Set War3Path',
      openWar3Path: 'Open War3 Path',
      setExportPath: 'Set Export Path',
      openExportPath: 'Open Export Path',
      resetPath: 'Right Click To Reset',
      resetDialog: {
        title: 'Reset',
        message: {
          war3: 'Reset War3 Path?',
          export: 'Reset Export Path?',
        },
      },
      team: {
        add: 'Add Team',
        name: 'Team Name',
        select: 'Select Team',
        notice: 'Please Select Team',
        view: 'View Team',
      },
      save: {
        select: 'Select Save File',
        notice: 'Please Select Save File',
        view: 'View Save History',
      },
      listenOn: 'Listen On',
      listenOff: 'Listen Off',
      scale: 'Scale',
      about: 'About',
      releaseUrl: '更新地址',
      h5: '速查H5',
      qq: '交流反馈群',
      ps: '打广告属于弟弟行为，无奈度娘疯狂吞链......',
    },
    good: {
      operations: '',
      image: 'Image',
      heroLimit: 'Limit',
      level: 'Level',
      quality: 'Quality/Info',
      limit: 'Limit',
      exclusives: 'Exclusives',
      overView: 'OverView',
      calc: 'Calc',
      have: 'Yes',
      searchPlaceholder: 'Input Search Text',
      dropFrom: 'From(Unit Drop)',
      buildFrom: 'From(Item Build)',
      makeTo: 'Build Item List',
      unitAttr: 'Unit Attributies',
      bossDrop: 'Unit Drops',
    },
    calc: {
      saveName: 'Calc Info',
      num: 'Num',
      count: 'Count',
      requireCount: 'Require Count',
      requireChooseCount: 'Sum Count',
      necessaryItem: 'Necessary Item',
      unNecessaryItem: 'Unnecessary Item',
      chooseItem: 'Choose Item',
      alreadyHave: 'Have',
    },
    mdx: {
      selectAnimation: 'Select Anim',
      selectWing: 'Select Wing',
      selectHelmet: 'Select Helmet',
      selectRing: 'Select Ring',
    },
    targetPanel: {
      clearCache: 'Clear Cache',
      deleteTarget: 'Delete Target',
      getDeleteTargetNotice: (name: string) => `Delete【${name}】`,
      searchPlaceholder: 'Input Search Text',
      toggle: 'Toggle',
      addTarget: 'Add Target',
      targetName: 'Target Name',
    },
    team: {
      image: 'Image',
      name: 'Name',
      count: 'Count',
      member: 'Member',
      analysisTitle: 'Analisis Result',
      add: 'Add',
      chooseHero: 'Choose Hero',
      mamberName: 'Member Name',
      split: 'Split',
      allMembersRequireAnalysis: 'All Analysis',
      deleteTeam: 'Delete Team',
      deleteTeamDialog: {
        title: 'Delete',
        getDeleteTeamNotice: (name: string) => `Delete【${name}】`,
      },
      deleteMemberDialog: {
        title: 'Delete',
        getDeleteMemberNotice: (team: string, member: string) => `Delete【${team}】=>【${member}】`,
      },
      getAddedNotice: {
        panel: (name: string) => `${name}added to Panel`,
        bag: (name: string) => `${name}added to Bag`,
        target: (name: string) => `${name}added to Target`,
      },
      getSplitTitle: (name: string) => `【${name}】All Split`,
      searchPlaceholder: 'Input Search Text',
      save: 'Save',
      cache: 'Cache',
      panel: 'Panel',
      target: 'Target',
      bag: 'Bag',
      delete: 'Delete',
      createDate: 'Ctrate Time：',
    },
    activity: {
      newYear: 'NewYear',
      april: 'April',
      summer: 'Summer',
      halloween: 'Halloween',
      no: 'No',
      image: 'Image',
      name: 'Name',
      skin: 'Skin',
      lossWarning: 'Was Ignored ^_^',
    },
    hero: {
      image: 'Image',
      name: 'Name',
      skill: 'Skill(Click To Change Exclusive)',
      exclusive: 'Exclusive(Click To Change Skill)',
    },
    record: {
      refresh: 'Refresh',
      deleteHistories: 'Delete Histories',
      deleteHistoriesDialog: {
        title: 'Delete Histories',
        content: 'Delete Old Histories',
      },
      deleteSaveFile: 'Delete Program Record',
      deleteSaveFileDialog: {
        getTitle: (name: string) => `Delete【${name}】?`,
        content: 'Notice:【Only Affect With Program】',
      },
      codes: 'Codes(Click To Change Items)',
      items: 'Items(Click To Change Codes)',
      time: 'Time',
      operations: 'Operations',
      copy: 'Copy',
      getCopySuccessText: (no: number, chunkNum: number) =>
        `Copy${no}${chunkNum ? `【Chunk${chunkNum}】` : ''}Success!`,
      delete: 'Delete',
    },
    replay: {
      title: 'Drag[nwg/w3g](Some Reps May Not Working)',
      copyToClipboard: 'Click To Copy',
      copySuccess: 'Copyed Success',
    },
    unit: {
      image: 'Image',
      name: 'Name',
      drops: 'Drops',
      stage: 'Stage',
    },
    footer: {
      thanks: 'Thanks Every One ^_^',
      split: 'Split',
      analysis: 'Analysis',
      calc: 'Calc',
      targetSplit: 'Target Split',
      getCopySuccessText: (name: string, chunkNum: number) =>
        `Copy【${name}】Code${chunkNum ? `【Chunk${chunkNum}】` : ''}Success!`,
      copy: 'Copy',
    },
  },
};

export default enLocal;
