export default {
  hp: 'hp',
  mp: 'mp',
  atk: '攻',
  def: '防',
  str: '力',
  agi: '敏',
  int: '智',
  mainAttrInc: '主属',
  atkSpeed: '攻速',
  // 'moveSpeed': '移速',
  abilityDamageInc: '技伤',
  sufferDamageDec: '减伤',
  magicDefInc: '魔抗',
  hpInc: '回血',
  stillDamageInc: '续伤',
  atkDamageInc: '攻伤',
  mpInc: '回蓝',
  hpRegenInc: '恢复',
  sufferCureInc: '治疗',
  missInc: '闪避',
  punchAsChanceInc: '倍击',
  punchChanceInc: '暴击',
  resurrectionTimeDec: '读秒',
  expInc: 'exp',
  iceDamageInc: '冰/水',
  fireDamageInc: '火',
  windAttrInc: '风',
  natureAttrInc: '自然',
  // 'effect': '特效',
};
