export default {
  name: '名字',
  umpr: '魔法回复',
  uagi: '初始敏捷',
  uint: '初始智力',
  uhpr: '生命回复',
  ustr: '初始力量',
  umvs: '基础速度',
  upro: '称谓',
  // unam: '名字',
  ussi: '图标-计分屏',
  uico: '图标-游戏界面',
  ua1c: '攻击1-攻击间隔',
  usid: '视野范围(白天)',
  usin: '视野范围(夜晚)',
  upra: '主要属性',
  uarm: '装甲类型',
  uacq: '主动攻击范围',
  udef: '基础护甲',
  ua1t: '攻击1-攻击类型',
  ua1b: '攻击1-基础伤害',
  uhpm: '生命最大值',
  udty: '护甲类型',
  ucol: '碰撞体积',
  uhrt: '生命回复类型',
  umvh: '高度',
  umas: '最大速度',
  umis: '最小速度',
};
