export default {
  自然之翼: { model: 'FairyWing', location: 'Sprite Ref' },
  蝙蝠之翼: { model: 'IllidianWing', location: 'Chest Ref' },
  伯爵的披风: { model: 'HHY', location: 'Sprite Ref' },
  龙翼: { model: 'EWING', location: 'Sprite Ref' },
  腐败水晶之翼: { model: 'LichWingBlue', location: 'Chest Ref' },
  堕落的火焰魂翼: { model: 'HLY', location: 'Sprite Ref' },
  冰极天雪魂翼: { model: 'ShivasWings', location: 'Chest Ref' },
  恶魔骨翼: { model: 'IllidanWings', location: 'Sprite Ref' },
  怒焱魂翼: { model: 'JHY', location: 'Sprite Ref' },
  霜魂女神之翼: { model: 'JDY2', location: 'Chest Ref' },
  信仰斗篷: { model: 'Wing01', location: 'Sprite Ref' },
  '星辰闪耀 圣堂之翼': { model: 'LichWingYellow', location: 'Chest Ref' },
  耀目星芒魂翼: { model: 'GaiaWings', location: 'Chest Ref' },
  地狱熔岩火凰羽翼: { model: 'YY', location: 'Sprite Ref' },
  亡者灵魂: { model: 'WingOfTheLucifer', location: 'Chest Ref' },
  暗黑不朽魂翼: { model: 'zm-chib-zi', location: 'Chest Ref' },
  魔音护魂之翼: { model: 'YH6', location: 'Head Ref' },
  飞星流彩碎翼: { model: 'Wings_LiuYi1', location: 'Chest Ref' },
  '狂暴 堕落统治魂翼': { model: 'Purple Abyss Wing', location: 'Chest Ref' },
  幻想霜寒魂翼: { model: 'ShivasWings_Dark', location: 'Chest Ref' },
  '祈明 神谕血翼': { model: 'WingBlack', location: 'Chest Ref' },
  '遂宇玄芒 灵仙魂翼': { model: 'FairyBlessing', location: 'Origin Ref' },
  '净空 至上祝福羽翼': { model: 'ArchangelWing', location: 'Chest Ref' },
  海蚀翅膀: { model: 'YH7', location: 'Chest Ref' },
};
